select as_of_yyyyqq,
  owner_role_vp_team as sales_region,
  owner_role_dir_team as sales_subregion,
  case when amount_as_of < 1000 then "~ 1K" when amount_as_of < 5000 then "1K ~ 5K" when amount_as_of < 10000 then "5K ~ 10K" when amount_as_of < 25000 then "10K ~ 25K" else "25K ~" end as amount_band,
  case when lead_source_derived = "Expansion" then "Expansion"
       when lead_source_derived = "Outbound" then "Outbound"
       when lead_source_derived in ( "BIME Trial","Chat Trial","Contact Us","Demo Request","Field","Gated Resource","Non-Trial Other","Social","Support Trial","Webinar Request" ) then "Inbound"
       else "Other" end as subtype,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 then amount_as_of end ) as created_as_of,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 then 1 end ) as created_as_of_count,
  string_agg( case when as_of_type = "Current doq" and created_quarter = 0 and amount_as_of >= 5000 then substr(id,1,15) end ) as created_as_of_ids,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of < 0 then amount_as_of end ) as created_as_of_prior,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of = 0 then amount_as_of end ) as inquarter_as_of,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") then amount_as_of end ) as inquarter_as_of_closed,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of = 0 and status_as_of = "Lost" then amount_as_of end ) as inquarter_as_of_lost,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of = 0 and status_as_of = "Open" then amount_as_of end ) as inquarter_as_of_open,
  string_agg( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of = 0 and amount_as_of >= 5000 then substr(id,1,15) end ) as inquarter_as_of_ids,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of = 1 then amount_as_of end ) as created_as_of_next,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of = 2 then amount_as_of end ) as created_as_of_three,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and close_quarter_as_of > 2 then amount_as_of end ) as created_as_of_four,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 then amount end ) as created,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and status in ("Closed","Signed") then amount end ) as created_closed,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and status = "Lost" then amount end ) as created_lost,
  sum( case when as_of_type = "Current doq" and created_quarter = 0 and status = "Open" then amount end ) as created_open,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") then amount_as_of end ) as signed_as_of,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") then 1 end ) as signed_as_of_count,
  string_agg( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") and amount_as_of >= 5000 then substr(id,1,15) end ) as signed_as_of_ids,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") and close_quarter_rel_created < 0 then amount_as_of end ) as signed_as_of_prior,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") and close_quarter_rel_created = 0 then amount_as_of end ) as signed_as_of_inquarter,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") and close_quarter_rel_created = 1 then amount_as_of end ) as signed_as_of_next,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") and close_quarter_rel_created = 2 then amount_as_of end ) as signed_as_of_three,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of in ("Closed","Signed") and close_quarter_rel_created > 2 then amount_as_of end ) as signed_as_of_four,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Lost" then amount_as_of end ) as lost_as_of,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" then amount_as_of end ) as open_as_of,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created = 0 and status_as_of = "Open" then amount_as_of end ) as open_as_of_0,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created = 1 and status_as_of = "Open" then amount_as_of end ) as open_as_of_1,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created = 2 and status_as_of = "Open" then amount_as_of end ) as open_as_of_2,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created > 2 and status_as_of = "Open" then amount_as_of end ) as open_as_of_3,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" then 1 end ) as open_as_of_count,
  string_agg( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and amount_as_of >= 5000 then substr(id,1,15) end ) as open_as_of_ids,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and ceil(close_doq_as_of/7) >= 13 then amount_as_of end ) as open_as_of_13,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created = 0 and status_as_of = "Open" and ceil(close_doq_as_of/7) >= 13 then amount_as_of end ) as open_as_of_13_0,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created = 1 and status_as_of = "Open" and ceil(close_doq_as_of/7) >= 13 then amount_as_of end ) as open_as_of_13_1,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created = 2 and status_as_of = "Open" and ceil(close_doq_as_of/7) >= 13 then amount_as_of end ) as open_as_of_13_2,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and close_quarter_rel_created > 2 and status_as_of = "Open" and ceil(close_doq_as_of/7) >= 13 then amount_as_of end ) as open_as_of_13_3,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and ceil(close_doq_as_of/7) >= 13 then 1 end ) as open_as_of_13_count,
  string_agg( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and amount_as_of >= 5000 and ceil(close_doq_as_of/7) >= 13 then substr(id,1,15) end ) as open_as_of_13_ids,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" then amount_as_of end ) as open_as_of_next,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and close_quarter_rel_created = 1 and status_as_of = "Open" then amount_as_of end ) as open_as_of_next_1,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and close_quarter_rel_created = 2 and status_as_of = "Open" then amount_as_of end ) as open_as_of_next_2,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and close_quarter_rel_created > 2 and status_as_of = "Open" then amount_as_of end ) as open_as_of_next_3,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" then 1 end ) as open_as_of_next_count,
  string_agg( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and amount_as_of >= 5000 then substr(id,1,15) end ) as open_as_of_next_ids,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 2 and status_as_of = "Open" then amount_as_of end ) as open_as_of_three,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of > 2 and status_as_of = "Open" then amount_as_of end ) as open_as_of_four,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" then amount end ) as `open`,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status in ("Closed","Signed") then amount end ) as open_closed,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status = "Lost" then amount end ) as open_lost,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status = "Open" then amount end ) as open_open,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter > 0 then amount end ) as open_pushed,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter < 0 then amount end ) as open_pulled,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and ceil(close_doq_as_of/7) >= 13 then amount end ) as `open_13`,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status in ("Closed","Signed") and ceil(close_doq_as_of/7) >= 13 then amount end ) as open_13_closed,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status = "Lost" and ceil(close_doq_as_of/7) >= 13 then amount end ) as open_13_lost,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status = "Open" and ceil(close_doq_as_of/7) >= 13 then amount end ) as open_13_open,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter > 0 and ceil(close_doq_as_of/7) >= 13 then amount end ) as open_13_pushed,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter < 0 and ceil(close_doq_as_of/7) >= 13 then amount end ) as open_13_pulled,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" then amount end ) as open_next,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter = 1 and status in ("Closed","Signed") then amount end ) as open_next_closed,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter = 1 and status = "Lost" then amount end ) as open_next_lost,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter = 1 and status = "Open" then amount end ) as open_next_open,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter > 1 then amount end ) as open_next_pushed,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter < 1 then amount end ) as open_next_pulled,
  string_agg( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter < 1 then substr(id,1,15) end ) as open_next_pulled_ids,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter < 1 and status in ("Closed","Signed") then amount end ) as open_next_pulled_closed,
  sum( case when as_of_type = "Current doq" and close_quarter_as_of = 1 and status_as_of = "Open" and close_quarter < 1 and status = "Lost" then amount end ) as open_next_pulled_lost,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 then amount_as_of end ) as created_as_of_eoq,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 then 1 end ) as created_as_of_eoq_count,
  string_agg( case when as_of_type = "End of quarter" and created_quarter = 0 and amount_as_of >= 5000 then substr(id,1,15) end ) as created_as_of_eoq_ids,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and close_quarter_as_of < 0 then amount_as_of end ) as created_as_of_eoq_prior,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and close_quarter_as_of = 0 then amount_as_of end ) as inquarter_as_of_eoq,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and close_quarter_as_of = 1 then amount_as_of end ) as created_as_of_eoq_next,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and close_quarter_as_of = 2 then amount_as_of end ) as created_as_of_eoq_three,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and close_quarter_as_of > 2 then amount_as_of end ) as created_as_of_eoq_four,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 then amount end ) as created_eoq,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and ( stage_name in ( "02 - Discovery","03 - Solution Review","04 - Solution Validation","05 - Contracting / Verbal","06 - Signed","Failed Finance Audit","Pending Sales Review","07 - Closed" ) or stage_name_lost not in ( "01 - Qualifying" )) then amount end ) as created_eoq_2,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and ( stage_name in ( "03 - Solution Review","04 - Solution Validation","05 - Contracting / Verbal","06 - Signed","Failed Finance Audit","Pending Sales Review","07 - Closed" ) or stage_name_lost not in ( "01 - Qualifying","02 - Discovery" )) then amount end ) as created_eoq_3,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and ( stage_name in ( "04 - Solution Validation","05 - Contracting / Verbal","06 - Signed","Failed Finance Audit","Pending Sales Review","07 - Closed" ) or stage_name_lost not in ( "01 - Qualifying","02 - Discovery","03 - Solution Review" )) then amount end ) as created_eoq_4,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and ( stage_name in ( "05 - Contracting / Verbal","06 - Signed","Failed Finance Audit","Pending Sales Review","07 - Closed" ) or stage_name_lost not in ( "01 - Qualifying","02 - Discovery","03 - Solution Review","04 - Solution Validation" )) then amount end ) as created_eoq_5,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and ( stage_name in ( "06 - Signed","Failed Finance Audit","Pending Sales Review","07 - Closed" ) or stage_name_lost not in ( "01 - Qualifying","02 - Discovery","03 - Solution Review","04 - Solution Validation","05 - Contracting / Verbal" )) then amount end ) as created_eoq_6,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and status in ("Closed","Signed") then amount end ) as created_eoq_closed,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and status = "Lost" then amount end ) as created_eoq_lost,
  sum( case when as_of_type = "End of quarter" and created_quarter = 0 and status = "Open" then amount end ) as created_eoq_open,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter_rel_created = 1 then amount_as_of end ) as open_as_of_soq_1,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter_rel_created = 2 then amount_as_of end ) as open_as_of_soq_2,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter_rel_created = 3 then amount_as_of end ) as open_as_of_soq_3,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter_rel_created > 3 then amount_as_of end ) as open_as_of_soq_4,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" then 1 end ) as open_as_of_soq_count,
  string_agg( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and amount_as_of >= 5000 then substr(id,1,15) end ) as open_as_of_soq_ids,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" then amount end ) as open_soq,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status in ("Closed","Signed") then amount end ) as open_soq_closed,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status = "Lost" then amount end ) as open_soq_lost,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter != 0 then amount end ) as open_soq_pushed,
  sum( case when as_of_type = "Quarter start" and close_quarter_as_of = 0 and status_as_of = "Open" and close_quarter = 0 and status = "Open" then amount end ) as open_soq_open,
  null as signed,
  null as signed_count,
  null as signed_ids,
  null as signed_prior,
  null as signed_inquarter,
  null as signed_next,
  null as signed_three,
  null as signed_four,
  null as lost,
  null as lost_count,
  null as lost_inquarter,
  null as lost_1,
  null as lost_2,
  null as lost_3,
  null as lost_4,
  null as lost_5
from `edw-prod-153420.gtm_operations_general.pipeline` where date_set = "quarters"
group by as_of_yyyyqq, sales_region, sales_subregion, amount_band, subtype
union all select close_yyyyqq,
  owner_role_vp_team,
  owner_role_dir_team,
  case when booking_amount < 1000 then "~ 1K" when booking_amount < 5000 then "1K ~ 5K" when booking_amount < 10000 then "5K ~ 10K" when booking_amount < 25000 then "10K ~ 25K" else "25K ~" end as amount_band,
  case when lead_source_derived = "Expansion" then "Expansion"
       when lead_source_derived = "Outbound" then "Outbound"
       when lead_source_derived in ( "BIME Trial","Chat Trial","Contact Us","Demo Request","Field","Gated Resource","Non-Trial Other","Social","Support Trial","Webinar Request" ) then "Inbound"
       else "Other" end as subtype,
  null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,
  null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,
  null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,
  null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,
  sum( case when status = "Closed" then booking_amount end ) as signed,
  sum( case when status = "Closed" then 1 end ) as signed_count,
  string_agg( case when status = "Closed" and booking_amount >= 5000 then substr(id,1,15) end ) as signed_ids,
  sum( case when status = "Closed" and close_quarter_rel_created < 0 then booking_amount end ) as signed_prior,
  sum( case when status = "Closed" and close_quarter_rel_created = 0 then booking_amount end ) as signed_inquarter,
  sum( case when status = "Closed" and close_quarter_rel_created = 1 then booking_amount end ) as signed_next,
  sum( case when status = "Closed" and close_quarter_rel_created = 2 then booking_amount end ) as signed_three,
  sum( case when status = "Closed" and close_quarter_rel_created > 2 then booking_amount end ) as signed_four,
  sum( case when status = "Lost" then booking_amount end ) as lost,
  sum( case when status = "Lost" then 1 end ) as lost_count,
  sum( case when status = "Lost" and close_quarter_rel_created = 0 then booking_amount end ) as lost_inquarter,
  sum( case when status = "Lost" and stage_name_lost = "01 - Qualifying" then booking_amount end ) as lost_1,
  sum( case when status = "Lost" and stage_name_lost = "02 - Discovery" then booking_amount end ) as lost_2,
  sum( case when status = "Lost" and stage_name_lost = "03 - Solution Review" then booking_amount end ) as lost_3,
  sum( case when status = "Lost" and stage_name_lost = "04 - Solution Validation" then booking_amount end ) as lost_4,
  sum( case when status = "Lost" and stage_name_lost = "05 - Contracting / Verbal" then booking_amount end ) as lost_5
from `edw-prod-153420.gtm_operations_general.opportunities`
where close_date >= "2015-01-01" and close_date < "2018-10-01" and status in ("Closed","Lost")
group by 1, 2, 3, 4, 5
order by 1 desc, 2, 3, 4, 5;


select *
from gtm_operations_general.pipeline
where owner_role_vp_team = "APAC"
  and date_set = "quarters"
  and as_of_type = "End of w12"
  and status_as_of in ("Open","Signed")
  and close_quarter_as_of >= 1
  and status = "Closed"
  and close_quarter = 0
order by close_date desc, amount desc;
  
  